sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.6

cache:
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=./tmp/wp-cli-phar

before_script:
  - ./bin/bootstrap

script: ./bin/test
